include:
  - board: nice_nano_v2
    shield: charybdis_left oled_adapter_pro_micro_128x32
  - board: nice_nano_v2
    shield: charybdis_right oled_adapter_pro_micro_128x32
  # - board: nice_nano_v2
  #   shield: settings_reset
