include:
  - board: nice_nano_v2
    shield: charybdis_left nice_view_adapter
  - board: nice_nano_v2
    shield: charybdis_right nice_view_adapter
  # - board: nice_nano_v2
  #   shield: settings_reset
