manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # - name: zmkfirmware
    #   url-base: https://github.com/petejohanson
    - name: inorichi
      url-base: https://github.com/inorichi
  projects:
    # - name: zmk
    #   remote: zmkfirmware
    #   revision: feat/pointers-move-scroll
    #   import: app/west.yml
    - name: zmk
      repo-path: zmk
      revision: main
      remote: zmkfirmware
      import: true
    - name: zmk-pmw3610-driver
      remote: inorichi
      revision: main
  self:
    path: config
